import type { SqlFragment } from '@tapcrm/authz';
import type { RequestContext } from '../../../platform/dal/context.js';
import { db, type Tx } from '../../../platform/dal/db.js';
import { sql } from '../../../platform/dal/sql.js';
import type { CallbackStatus, LeadCallback } from './types.js';

const CALLBACK_SELECT = sql`SELECT c.id, c.organization_id AS "organizationId", c.lead_id AS "leadId", l.lead_number::text AS "leadNumber", l.contact_name AS "leadContactName", c.owner_id AS "ownerId", owner.full_name AS "ownerName", c.scheduled_at AS "scheduledAt", c.reason, c.status, c.outcome, c.parent_callback_id AS "parentCallbackId", organization.timezone AS "organizationTimezone",
  COALESCE((SELECT json_agg(json_build_object('id', r.id, 'reminderType', r.reminder_type, 'scheduledAt', r.scheduled_at, 'deliveries', COALESCE((SELECT json_agg(json_build_object('id', d.id, 'recipientId', d.recipient_id, 'channel', d.channel, 'status', d.status, 'scheduledAt', d.scheduled_at, 'sentAt', d.sent_at, 'deliveredAt', d.delivered_at, 'failedAt', d.failed_at, 'detail', d.detail) ORDER BY d.channel) FROM lead_callback_reminder_delivery d WHERE d.organization_id = r.organization_id AND d.reminder_id = r.id), '[]'::json)) ORDER BY r.scheduled_at) FROM lead_callback_reminder r WHERE r.organization_id = c.organization_id AND r.callback_id = c.id), '[]'::json) AS reminders,
  c.completed_at AS "completedAt", c.missed_at AS "missedAt", c.cancelled_at AS "cancelledAt", c.created_by AS "createdBy", c.created_at AS "createdAt", c.updated_at AS "updatedAt" FROM lead_callback c JOIN app_user owner ON owner.organization_id = c.organization_id AND owner.id = c.owner_id JOIN lead l ON l.organization_id = c.organization_id AND l.id = c.lead_id JOIN organization ON organization.id = c.organization_id LEFT JOIN team ON team.organization_id = l.organization_id AND team.id = l.sales_team_id`;
function mapCallback(row: LeadCallback): LeadCallback { return { ...row, scheduledAt: new Date(row.scheduledAt), completedAt: row.completedAt ? new Date(row.completedAt) : null, missedAt: row.missedAt ? new Date(row.missedAt) : null, cancelledAt: row.cancelledAt ? new Date(row.cancelledAt) : null, createdAt: new Date(row.createdAt), updatedAt: new Date(row.updatedAt) }; }
export async function listCallbacks(ctx: RequestContext, filter: SqlFragment): Promise<LeadCallback[]> { const rows = await db.query<LeadCallback>(ctx, sql`${CALLBACK_SELECT} WHERE c.organization_id = ${ctx.organizationId} AND ${filter} ORDER BY c.scheduled_at ASC`); return rows.map(mapCallback); }
export async function findCallback(ctx: RequestContext, id: string): Promise<LeadCallback | null> { const row = await db.maybeOne<LeadCallback>(ctx, sql`${CALLBACK_SELECT} WHERE c.organization_id = ${ctx.organizationId} AND c.id = ${id}`); return row ? mapCallback(row) : null; }
export async function findCallbackTx(tx: Tx, organizationId: string, id: string): Promise<LeadCallback | null> { const row = await tx.maybeOne<LeadCallback>(sql`${CALLBACK_SELECT} WHERE c.organization_id = ${organizationId} AND c.id = ${id}`); return row ? mapCallback(row) : null; }
export async function loadCallbackResource(ctx: RequestContext, id: string) { return db.maybeOne<{ id: string; organizationId: string; leadId: string; ownerId: string; status: CallbackStatus; salesTeamId: string | null; salesPoolId: string | null; departmentId: string | null }>(ctx, sql`SELECT c.id, c.organization_id AS "organizationId", c.lead_id AS "leadId", c.owner_id AS "ownerId", c.status, l.sales_team_id AS "salesTeamId", l.sales_pool_id AS "salesPoolId", team.department_id AS "departmentId" FROM lead_callback c JOIN lead l ON l.organization_id = c.organization_id AND l.id = c.lead_id LEFT JOIN team ON team.organization_id = l.organization_id AND team.id = l.sales_team_id WHERE c.organization_id = ${ctx.organizationId} AND c.id = ${id}`).then((row) => row ? { type: 'callback' as const, ...row } : null); }
export async function insertCallback(tx: Tx, organizationId: string, input: { leadId: string; ownerId: string; scheduledAt: Date; reason: string | null; parentCallbackId?: string | null; createdBy: string }): Promise<string> { const row = await tx.one<{ id: string }>(sql`INSERT INTO lead_callback (organization_id, lead_id, owner_id, scheduled_at, reason, parent_callback_id, created_by) VALUES (${organizationId}, ${input.leadId}, ${input.ownerId}, ${input.scheduledAt}, ${input.reason}, ${input.parentCallbackId ?? null}, ${input.createdBy}) RETURNING id`); return row.id; }
export async function markCallbackRescheduled(tx: Tx, organizationId: string, id: string): Promise<void> { await tx.query(sql`UPDATE lead_callback SET status = 'rescheduled' WHERE organization_id = ${organizationId} AND id = ${id} AND status = 'pending'`); }
export async function updateCallbackStatus(tx: Tx, organizationId: string, id: string, status: Exclude<CallbackStatus, 'pending' | 'rescheduled'>, outcome: string | null): Promise<void> { const timestamp = status === 'completed' ? sql`completed_at = now()` : status === 'missed' ? sql`missed_at = now()` : status === 'cancelled' ? sql`cancelled_at = now()` : sql`updated_at = updated_at`; await tx.query(sql`UPDATE lead_callback SET status = ${status}, outcome = ${outcome}, ${timestamp} WHERE organization_id = ${organizationId} AND id = ${id} AND status = 'pending'`); }
export async function getStalledConfiguration(ctx: RequestContext): Promise<number> { const row = await db.maybeOne<{ stalledAfterDays: number }>(ctx, sql`SELECT stalled_after_days AS "stalledAfterDays" FROM lead_lifecycle_configuration WHERE organization_id = ${ctx.organizationId}`); return row?.stalledAfterDays ?? 7; }
export async function listStalledCallbacks(ctx: RequestContext): Promise<LeadCallback[]> { return listCallbacks(ctx, sql`c.status = 'missed'`); }
