import { useEffect, useMemo, useState } from 'react';
import { Button, Card, Empty, Loading, Notice, Page, Select } from '../../ui/components.js';
import { calendarMonth, validDateOnly } from '../../ui/calendar-model.js';
import { listShifts, type ShiftTemplate } from '../api/shiftsApi.js';
import { attendanceErrorMessage, getDailyAttendanceReport, getMonthlyAttendanceReport, requestDailyAttendanceExport, requestMonthlyAttendanceExport, type DailyAttendanceRow, type MonthlyAttendanceRow } from './attendanceApi.js';
import { AttendanceKpis, AttendanceLegend } from './AttendanceVisuals.js';

type Mode = 'daily' | 'monthly';
const today = (): string => new Date().toISOString().slice(0, 10);
const time = (value: string | null): string => value ? new Date(value).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: false }) : '—';
const duration = (value: number): string => `${Math.floor(value / 60)}h ${value % 60}m`;
const dailyStatus = (row: DailyAttendanceRow): string => row.status ?? (row.arrivalAt ? 'In progress' : 'No punch');
const code = (record: { status: string | null; dayType?: string | null; isWfh: boolean } | undefined): string => !record ? '—' : record.isWfh && record.status === 'present' ? 'P·WFH' : record.status === 'present' ? 'P' : record.status === 'half-day' ? 'HD' : record.status === 'absent' ? 'Ab' : record.status === 'leave' || record.status === 'half-day-leave' ? 'L' : record.status === 'holiday' || record.dayType === 'holiday' ? 'H' : record.status ?? '—';

export function AttendanceReportPage({ canExport = false }: { canExport?: boolean }): React.JSX.Element {
  const now = today(); const [mode, setMode] = useState<Mode>('daily'); const [date, setDate] = useState(now); const [month, setMonth] = useState(now.slice(5, 7)); const [year, setYear] = useState(now.slice(0, 4)); const [shiftId, setShiftId] = useState(''); const [format, setFormat] = useState<'csv' | 'xlsx'>('csv'); const [shifts, setShifts] = useState<ShiftTemplate[]>([]);
  const [dailyRows, setDailyRows] = useState<DailyAttendanceRow[]>([]); const [monthlyRows, setMonthlyRows] = useState<MonthlyAttendanceRow[]>([]); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [totalPages, setTotalPages] = useState(1); const [loading, setLoading] = useState(true); const [exporting, setExporting] = useState(false); const [error, setError] = useState<string | null>(null);
  const months = useMemo(() => Array.from({ length: 12 }, (_, index) => ({ value: String(index + 1).padStart(2, '0'), label: new Date(Date.UTC(2026, index, 1)).toLocaleString('en-IN', { month: 'long', timeZone: 'UTC' }) })), []); const years = useMemo(() => Array.from({ length: 7 }, (_, index) => String(Number(now.slice(0, 4)) - 3 + index)), [now]); const dates = calendarMonth(`${year}-${month}`).filter((item) => item.startsWith(`${year}-${month}`));
  useEffect(() => { void listShifts().then(setShifts).catch((cause) => setError(attendanceErrorMessage(cause, 'Unable to load shifts.'))); }, []);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(null); const query: Record<string, string> = { page: String(page), pageSize: '50' }; if (shiftId) query['shiftId'] = shiftId; void (async () => { try { if (mode === 'daily') { const result = await getDailyAttendanceReport({ ...query, date }, controller.signal); setDailyRows(result.rows); setTotal(result.total); setTotalPages(result.totalPages); } else { const result = await getMonthlyAttendanceReport({ ...query, month, year }, controller.signal); setMonthlyRows(result.rows); setTotal(result.total); setTotalPages(result.totalPages); } } catch (cause) { if (!(cause instanceof Error && cause.name === 'AbortError')) setError(attendanceErrorMessage(cause, 'Unable to load the attendance report.')); } finally { setLoading(false); } })(); return () => controller.abort(); }, [mode, date, month, year, shiftId, page]);
  async function exportReport(): Promise<void> { setExporting(true); setError(null); try { const query: Record<string, string> = mode === 'daily' ? { date } : { month, year }; query['format'] = format; if (shiftId) query['shiftId'] = shiftId; const blob = mode === 'daily' ? await requestDailyAttendanceExport(query) : await requestMonthlyAttendanceExport(query); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = mode === 'daily' ? `attendance-daily-${date}.${format}` : `attendance-monthly-${year}-${month}.${format}`; link.click(); URL.revokeObjectURL(url); } catch (cause) { setError(attendanceErrorMessage(cause, 'Unable to export the attendance report.')); } finally { setExporting(false); } }
  return <Page eyebrow="HR · Attendance" title="Attendance Report" description="Daily and monthly attendance from stored calculated records.">
    <Card><div className="flex flex-wrap items-end gap-3"><div className="flex gap-2"><Button kind={mode === 'daily' ? 'primary' : 'secondary'} onClick={() => { setMode('daily'); setPage(1); }}>Daily</Button><Button kind={mode === 'monthly' ? 'primary' : 'secondary'} onClick={() => { setMode('monthly'); setPage(1); }}>Monthly</Button></div>{mode === 'daily' ? <label className="text-xs font-semibold text-app-muted"><span className="mb-2 block">Date</span><input type="date" value={date} onChange={(event) => { if (validDateOnly(event.target.value)) { setDate(event.target.value); setPage(1); } }} className="rounded-lg border border-app-border bg-app-background px-3 py-2.5 text-sm" /></label> : <><Select label="Month" value={month} onChange={(value) => { setMonth(value); setPage(1); }} options={months} /><Select label="Year" value={year} onChange={(value) => { setYear(value); setPage(1); }} options={years.map((value) => ({ value, label: value }))} /></>}<Select label="Shift" value={shiftId} onChange={(value) => { setShiftId(value); setPage(1); }} options={shifts.map((item) => ({ value: item.id, label: item.name }))} />{canExport && <><Select label="Export format" value={format} onChange={(value) => setFormat(value as 'csv' | 'xlsx')} options={[{ value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'XLSX' }]} /><Button disabled={exporting} onClick={() => void exportReport()}>{exporting ? 'Exporting…' : 'Export'}</Button></>}<Button kind="secondary" onClick={() => { setShiftId(''); setPage(1); }}>Reset</Button></div></Card>
    {!loading && !error && <Card className="mt-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">At-a-glance status</h2><p className="text-sm text-app-muted">{mode === 'daily' ? date : `${month}/${year}`} · {total} employees</p></div><AttendanceLegend /></div><div className="mt-4"><AttendanceKpis items={mode === 'daily' ? [{ label: 'Present', value: dailyRows.filter((row) => row.status === 'present' || row.arrivalAt).length, tone: 'border-emerald-200 dark:border-emerald-800' }, { label: 'WFH', value: dailyRows.filter((row) => row.isWfh).length, tone: 'border-sky-200 dark:border-sky-800' }, { label: 'Late', value: dailyRows.filter((row) => row.lateMinutes > 0).length, tone: 'border-amber-200 dark:border-amber-800' }, { label: 'No punch', value: dailyRows.filter((row) => !row.arrivalAt).length, tone: 'border-app-border' }] : [{ label: 'Employees', value: total }, { label: 'Present units', value: monthlyRows.reduce((sum, row) => sum + row.presentUnits, 0), tone: 'border-emerald-200 dark:border-emerald-800' }, { label: 'Absent units', value: monthlyRows.reduce((sum, row) => sum + row.absentUnits, 0), tone: 'border-rose-200 dark:border-rose-800' }, { label: 'WFH days', value: monthlyRows.reduce((sum, row) => sum + row.wfhDays, 0), tone: 'border-sky-200 dark:border-sky-800' }]} /></div></Card>}
    {error && <Notice error>{error}</Notice>}{loading && <Loading />}{!loading && !error && ((mode === 'daily' && dailyRows.length === 0) || (mode === 'monthly' && monthlyRows.length === 0)) && <Empty>{mode === 'daily' ? 'No employees or attendance data are available for this date and visibility scope.' : 'No attendance data are available for this month and shift selection.'}</Empty>}
    {!loading && !error && mode === 'daily' && dailyRows.length > 0 && <Card className="overflow-x-auto p-0"><table className="w-full min-w-[1100px] text-sm"><thead><tr className="border-b border-app-border bg-app-surface-raised text-left text-xs text-app-muted">{['Employee', 'Email/ID', 'Department', 'Team', 'Position', 'Designation', 'Shift', 'Punch in', 'Punch out', 'Worked', 'Break', 'Late', 'Overtime', 'WFH', 'Status'].map((label) => <th key={label} className="px-3 py-3">{label}</th>)}</tr></thead><tbody>{dailyRows.map((row) => <tr key={row.id} className="border-b border-app-border last:border-0"><td className="px-3 py-3 font-semibold">{row.fullName}</td><td className="px-3 py-3">{row.employeeId ?? '—'}</td><td className="px-3 py-3">{row.departmentName ?? '—'}</td><td className="px-3 py-3">{row.teamName ?? '—'}</td><td className="px-3 py-3">{row.positionName ?? '—'}</td><td className="px-3 py-3">{row.designationName ?? '—'}</td><td className="px-3 py-3">{row.shift?.kind ?? '—'}</td><td className="px-3 py-3">{time(row.arrivalAt)}</td><td className="px-3 py-3">{time(row.departureAt)}</td><td className="px-3 py-3">{duration(row.workedMinutes)}</td><td className="px-3 py-3">{duration(row.breakMinutes)}</td><td className="px-3 py-3">{row.lateMinutes}m</td><td className="px-3 py-3">{row.overtimeMinutes}m</td><td className="px-3 py-3">{row.isWfh ? 'Yes' : 'No'}</td><td className="px-3 py-3 font-semibold">{dailyStatus(row)}</td></tr>)}</tbody></table><Pagination page={page} totalPages={totalPages} total={total} onPage={setPage} /></Card>}
    {!loading && !error && mode === 'monthly' && monthlyRows.length > 0 && <Card className="overflow-hidden p-0"><div className="overflow-x-auto"><table className="min-w-[1200px] w-full text-sm"><thead><tr className="border-b border-app-border bg-app-surface-raised text-left text-xs text-app-muted"><th className="sticky left-0 z-10 min-w-52 bg-app-surface-raised px-4 py-3">Employee</th><th className="min-w-28 px-3 py-3">Shift</th>{dates.map((item) => <th key={item} className="min-w-12 px-2 py-3 text-center">{Number(item.slice(8))}</th>)}</tr></thead><tbody>{monthlyRows.map((row) => { const records = new Map(row.records.map((record) => [record.date, record])); return <tr key={row.id} className="border-b border-app-border"><td className="sticky left-0 z-10 bg-app-surface px-4 py-3"><p className="font-semibold">{row.fullName}</p><p className="text-xs text-app-muted">{row.employeeId ?? '—'} · {row.departmentName ?? '—'}</p></td><td className="px-3 py-3 text-xs text-app-muted">{row.shift?.kind ?? 'Multiple/—'}</td>{dates.map((item) => <td key={item} className="px-1 py-2 text-center text-xs font-bold">{code(records.get(item))}</td>)}</tr>; })}</tbody></table></div><div className="overflow-x-auto border-t border-app-border"><table className="w-full min-w-[1000px] text-sm"><thead><tr className="text-left text-xs text-app-muted"><th className="px-4 py-3">Employee totals</th><th className="px-3 py-3">Present</th><th className="px-3 py-3">Leave</th><th className="px-3 py-3">Absent</th><th className="px-3 py-3">Holiday</th><th className="px-3 py-3">WFH</th><th className="px-3 py-3">Late</th><th className="px-3 py-3">Worked</th><th className="px-3 py-3">Break</th><th className="px-3 py-3">Overtime</th></tr></thead><tbody>{monthlyRows.map((row) => <tr key={row.id} className="border-t border-app-border"><td className="px-4 py-2 font-semibold">{row.fullName}</td><td className="px-3 py-2">{row.presentUnits}</td><td className="px-3 py-2">{row.paidLeaveUnits + row.unpaidLeaveUnits}</td><td className="px-3 py-2">{row.absentUnits}</td><td className="px-3 py-2">{row.holidayUnits}</td><td className="px-3 py-2">{row.wfhDays}</td><td className="px-3 py-2">{row.lateDays} / {row.lateMinutes}m</td><td className="px-3 py-2">{duration(row.workedMinutes)}</td><td className="px-3 py-2">{duration(row.breakMinutes)}</td><td className="px-3 py-2">{row.overtimeMinutes}m</td></tr>)}</tbody></table></div><Pagination page={page} totalPages={totalPages} total={total} onPage={setPage} /></Card>}
  </Page>;
}

function Pagination({ page, totalPages, total, onPage }: { page: number; totalPages: number; total: number; onPage: (value: number) => void }): React.JSX.Element { return <div className="flex items-center justify-between gap-3 border-t border-app-border px-4 py-3 text-sm text-app-muted"><span>{total} employees · Page {page} of {totalPages}</span><span className="flex gap-2"><Button kind="secondary" disabled={page <= 1} onClick={() => onPage(page - 1)}>Previous</Button><Button kind="secondary" disabled={page >= totalPages} onClick={() => onPage(page + 1)}>Next</Button></span></div>; }
