import { useEffect, useMemo, useState } from 'react';
import { Button, Card, Empty, Loading, Notice, Page, Select } from '../../ui/components.js';
import { calendarDateLabel, validDateOnly } from '../../ui/calendar-model.js';
import { listShifts, type ShiftTemplate } from '../api/shiftsApi.js';
import { attendanceErrorMessage, getDailyLateReport, getEmployeeWiseReport, getMonthlyLateReport, requestDailyLateExport, requestMonthlyLateExport, type DailyLateRow, type EmployeeWiseReport, type MonthlyLateRow } from './attendanceApi.js';
import { AttendanceCalendar, AttendanceKpis, AttendanceLegend } from './AttendanceVisuals.js';

type Mode = 'daily' | 'monthly';
const today = (): string => new Date().toISOString().slice(0, 10);
const time = (value: string | null): string => value ? new Date(value).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: false }) : '—';

export function DailyLateReportPage({ canExport = false }: { canExport?: boolean }): React.JSX.Element {
  const now = today();
  const [mode, setMode] = useState<Mode>('daily');
  const [date, setDate] = useState(now); const [month, setMonth] = useState(now.slice(5, 7)); const [year, setYear] = useState(now.slice(0, 4));
  const [shiftId, setShiftId] = useState(''); const [format, setFormat] = useState<'csv' | 'xlsx'>('csv'); const [shifts, setShifts] = useState<ShiftTemplate[]>([]);
  const [dailyRows, setDailyRows] = useState<DailyLateRow[]>([]); const [monthlyRows, setMonthlyRows] = useState<MonthlyLateRow[]>([]); const [drilldown, setDrilldown] = useState<EmployeeWiseReport | null>(null);
  const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [totalPages, setTotalPages] = useState(1); const [loading, setLoading] = useState(true); const [exporting, setExporting] = useState(false); const [error, setError] = useState<string | null>(null);
  const months = useMemo(() => Array.from({ length: 12 }, (_, index) => ({ value: String(index + 1).padStart(2, '0'), label: new Date(Date.UTC(2026, index, 1)).toLocaleString('en-IN', { month: 'long', timeZone: 'UTC' }) })), []);
  const years = useMemo(() => Array.from({ length: 7 }, (_, index) => String(Number(now.slice(0, 4)) - 3 + index)), [now]);

  useEffect(() => { void listShifts().then(setShifts).catch((cause) => setError(attendanceErrorMessage(cause, 'Unable to load shifts.'))); }, []);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(null); const query: Record<string, string> = { page: String(page), pageSize: '50' }; if (shiftId) query['shiftId'] = shiftId; void (async () => { try { if (mode === 'daily') { const result = await getDailyLateReport({ ...query, date }, controller.signal); setDailyRows(result.rows); setTotal(result.total); setTotalPages(result.totalPages); } else { const result = await getMonthlyLateReport({ ...query, month, year }, controller.signal); setMonthlyRows(result.rows); setTotal(result.total); setTotalPages(result.totalPages); } } catch (cause) { if (!(cause instanceof Error && cause.name === 'AbortError')) setError(attendanceErrorMessage(cause, 'Unable to load the late report.')); } finally { setLoading(false); } })(); return () => controller.abort(); }, [mode, date, month, year, shiftId, page]);

  const queryForExport = (): Record<string, string> => { const query: Record<string, string> = mode === 'daily' ? { date } : { month, year }; query['format'] = format; if (shiftId) query['shiftId'] = shiftId; return query; };
  async function exportReport(): Promise<void> { setExporting(true); setError(null); try { const blob = mode === 'daily' ? await requestDailyLateExport(queryForExport()) : await requestMonthlyLateExport(queryForExport()); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = mode === 'daily' ? `late-daily-${date}.${format}` : `late-monthly-${year}-${month}.${format}`; link.click(); URL.revokeObjectURL(url); } catch (cause) { setError(attendanceErrorMessage(cause, 'Unable to export the late report.')); } finally { setExporting(false); } }
  async function openDrilldown(row: MonthlyLateRow): Promise<void> { setError(null); try { setDrilldown(await getEmployeeWiseReport(row.id, month, Number(year))); } catch (cause) { setError(attendanceErrorMessage(cause, 'Unable to load late dates.')); } }
  const reset = (): void => { setShiftId(''); setPage(1); };

  return <Page eyebrow="HR · Attendance" title="Daily Late Report" description="Review stored late-minute results by day or month.">
    <Card><div className="flex flex-wrap items-end gap-3"><div className="flex gap-2"><Button kind={mode === 'daily' ? 'primary' : 'secondary'} onClick={() => { setMode('daily'); setPage(1); setDrilldown(null); }}>Daily</Button><Button kind={mode === 'monthly' ? 'primary' : 'secondary'} onClick={() => { setMode('monthly'); setPage(1); setDrilldown(null); }}>Monthly</Button></div>{mode === 'daily' ? <label className="text-xs font-semibold text-app-muted"><span className="mb-2 block">Date</span><input type="date" value={date} onChange={(event) => { if (validDateOnly(event.target.value)) { setDate(event.target.value); setPage(1); } }} className="rounded-lg border border-app-border bg-app-background px-3 py-2.5 text-sm" /></label> : <><Select label="Month" value={month} onChange={(value) => { setMonth(value); setPage(1); }} options={months} /><Select label="Year" value={year} onChange={(value) => { setYear(value); setPage(1); }} options={years.map((value) => ({ value, label: value }))} /></>}<Select label="Shift" value={shiftId} onChange={(value) => { setShiftId(value); setPage(1); }} options={shifts.map((item) => ({ value: item.id, label: item.name }))} />{canExport && <><Select label="Export format" value={format} onChange={(value) => setFormat(value as 'csv' | 'xlsx')} options={[{ value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'XLSX' }]} /><Button disabled={exporting} onClick={() => void exportReport()}>{exporting ? 'Exporting…' : 'Export'}</Button></>}<Button kind="secondary" onClick={reset}>Reset</Button></div></Card>
    {!loading && !error && <Card className="mt-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Late overview</h2><p className="text-sm text-app-muted">{mode === 'daily' ? date : `${month}/${year}`} · {total} employees</p></div><AttendanceLegend /></div><div className="mt-4"><AttendanceKpis items={mode === 'daily' ? [{ label: 'Late employees', value: total, tone: 'border-amber-200 dark:border-amber-800' }, { label: 'Late minutes', value: dailyRows.reduce((sum, row) => sum + row.lateMinutes, 0) }, { label: 'WFH late', value: dailyRows.filter((row) => row.isWfh).length, tone: 'border-sky-200 dark:border-sky-800' }] : [{ label: 'Employees', value: total }, { label: 'Late days', value: monthlyRows.reduce((sum, row) => sum + row.lateDays, 0), tone: 'border-amber-200 dark:border-amber-800' }, { label: 'Total minutes', value: monthlyRows.reduce((sum, row) => sum + row.lateMinutes, 0) }, { label: 'Peak late', value: monthlyRows.reduce((max, row) => Math.max(max, row.maximumLateMinutes), 0) }]} /></div></Card>}
    {error && <Notice error>{error}</Notice>}{loading && <Loading />}{!loading && !error && ((mode === 'daily' && dailyRows.length === 0) || (mode === 'monthly' && monthlyRows.length === 0)) && <Empty>No late employees match this selection.</Empty>}
    {!loading && !error && mode === 'daily' && dailyRows.length > 0 && <Card className="overflow-x-auto p-0"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-app-border bg-app-surface-raised text-left text-xs text-app-muted">{['Employee', 'Department', 'Team', 'Position', 'Shift', 'Shift start', 'Punch in', 'Grace', 'Late', 'WFH'].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{dailyRows.map((row) => <tr key={row.id} className="border-b border-app-border last:border-0"><td className="px-4 py-3"><p className="font-semibold">{row.fullName}</p><p className="text-xs text-app-muted">{row.employeeId ?? '—'}</p></td><td className="px-4 py-3">{row.departmentName ?? '—'}</td><td className="px-4 py-3">{row.teamName ?? '—'}</td><td className="px-4 py-3">{row.positionName ?? '—'}</td><td className="px-4 py-3">{row.shift.kind ?? '—'}</td><td className="px-4 py-3">{row.shift.start ?? '—'}</td><td className="px-4 py-3">{time(row.arrivalAt)}</td><td className="px-4 py-3">{row.shift.graceMinutes ?? '—'}m</td><td className="px-4 py-3 font-bold text-amber-700 dark:text-amber-300">{row.lateMinutes}m</td><td className="px-4 py-3">{row.isWfh ? 'Yes' : 'No'}</td></tr>)}</tbody></table><Pagination page={page} totalPages={totalPages} total={total} onPage={setPage} /></Card>}
    {!loading && !error && mode === 'monthly' && monthlyRows.length > 0 && <Card className="overflow-x-auto p-0"><table className="w-full min-w-[800px] text-sm"><thead><tr className="border-b border-app-border bg-app-surface-raised text-left text-xs text-app-muted">{['Employee', 'Department', 'Team', 'Position', 'Late days', 'Total late', 'Average late', 'Maximum late', ''].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{monthlyRows.map((row) => <tr key={row.id} className="border-b border-app-border last:border-0"><td className="px-4 py-3"><p className="font-semibold">{row.fullName}</p><p className="text-xs text-app-muted">{row.employeeId ?? '—'}</p></td><td className="px-4 py-3">{row.departmentName ?? '—'}</td><td className="px-4 py-3">{row.teamName ?? '—'}</td><td className="px-4 py-3">{row.positionName ?? '—'}</td><td className="px-4 py-3">{row.lateDays}</td><td className="px-4 py-3">{row.lateMinutes}m</td><td className="px-4 py-3">{row.averageLateMinutes.toFixed(1)}m</td><td className="px-4 py-3">{row.maximumLateMinutes}m</td><td className="px-4 py-3"><Button kind="secondary" onClick={() => void openDrilldown(row)}>Late dates</Button></td></tr>)}</tbody></table><Pagination page={page} totalPages={totalPages} total={total} onPage={setPage} /></Card>}
    {drilldown && <Card><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold">{drilldown.employee.fullName} — late dates</h2><p className="mt-1 text-sm text-app-muted">{calendarDateLabel(`${year}-${month}-01`).replace(/\b\d+\b/, '')}</p></div><Button kind="secondary" onClick={() => setDrilldown(null)}>Close</Button></div><div className="mt-4"><AttendanceCalendar month={`${year}-${month}`} records={new Map(drilldown.records.filter((record) => record.minutes.late > 0).map((record) => [record.date, { status: 'present', isWfh: record.isWfh, lateMinutes: record.minutes.late }]))} /></div><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-app-border text-left text-xs text-app-muted"><th className="px-3 py-2">Date</th><th className="px-3 py-2">Shift start</th><th className="px-3 py-2">Punch in</th><th className="px-3 py-2">Late</th><th className="px-3 py-2">WFH</th></tr></thead><tbody>{drilldown.records.filter((record) => record.minutes.late > 0).map((record) => <tr key={record.date} className="border-b border-app-border"><td className="px-3 py-2">{record.date}</td><td className="px-3 py-2">{record.shift.start ?? '—'}</td><td className="px-3 py-2">{time(record.arrivalAt)}</td><td className="px-3 py-2 font-bold">{record.minutes.late}m</td><td className="px-3 py-2">{record.isWfh ? 'Yes' : 'No'}</td></tr>)}</tbody></table></div></Card>}
  </Page>;
}

function Pagination({ page, totalPages, total, onPage }: { page: number; totalPages: number; total: number; onPage: (page: number) => void }): React.JSX.Element { return <div className="flex flex-wrap items-center justify-between gap-3 border-t border-app-border px-4 py-3 text-sm text-app-muted"><span>{total} employees · Page {page} of {totalPages}</span><div className="flex gap-2"><Button kind="secondary" disabled={page <= 1} onClick={() => onPage(page - 1)}>Previous</Button><Button kind="secondary" disabled={page >= totalPages} onClick={() => onPage(page + 1)}>Next</Button></div></div>; }
