import { ApplicationError } from '../../errors.js';

export const ORGANIZATION_ERROR_CODES = {
  DEPARTMENT_NOT_FOUND: 'ORG_DEPARTMENT_NOT_FOUND',
  DEPARTMENT_CODE_EXISTS: 'ORG_DEPARTMENT_CODE_EXISTS',
  DEPARTMENT_INVALID: 'ORG_DEPARTMENT_INVALID',
  TEAM_NOT_FOUND: 'ORG_TEAM_NOT_FOUND',
  TEAM_NAME_EXISTS: 'ORG_TEAM_NAME_EXISTS',
  TEAM_DEPARTMENT_HAS_ACTIVE_MEMBERS: 'ORG_TEAM_DEPARTMENT_HAS_ACTIVE_MEMBERS',
  TEAM_DEPARTMENT_INVALID: 'ORG_TEAM_DEPARTMENT_INVALID',
  TEAM_KIND_INVALID: 'ORG_INVALID_TEAM_KIND',
  TEAM_PARENT_INVALID: 'ORG_INVALID_TEAM_PARENT',
  TEAM_LEAD_INVALID: 'ORG_INVALID_TEAM_LEAD',
  TEAM_MEMBER_INVALID: 'ORG_INVALID_TEAM_MEMBER',
  DESIGNATION_NOT_FOUND: 'ORG_DESIGNATION_NOT_FOUND',
  DESIGNATION_NAME_EXISTS: 'ORG_DESIGNATION_NAME_EXISTS',
  DESIGNATION_INACTIVE: 'ORG_DESIGNATION_INACTIVE',
  DESIGNATION_DEPARTMENT_INVALID: 'ORG_DESIGNATION_DEPARTMENT_INVALID',
  DESIGNATION_SPECIALIZATION_DUPLICATE: 'ORG_DESIGNATION_SPECIALIZATION_DUPLICATE',
  DESIGNATION_SPECIALIZATION_INVALID: 'ORG_DESIGNATION_SPECIALIZATION_INVALID',
  POSITION_NOT_FOUND: 'ORG_POSITION_NOT_FOUND',
  POSITION_CODE_EXISTS: 'ORG_POSITION_CODE_EXISTS',
  POSITION_DEPARTMENT_INVALID: 'ORG_POSITION_CROSS_DEPARTMENT',
  POSITION_CANNOT_BE_ROOT: 'ORG_POSITION_CANNOT_BE_ROOT',
  POSITION_LEVEL_CONFLICT: 'ORG_POSITION_LEVEL_CONFLICT',
  POSITION_LIMIT_EXCEEDED: 'ORG_POSITION_APPROVAL_LIMIT_EXCEEDED',
  POSITION_SEEDED_IMMUTABLE: 'ORG_POSITION_SEEDED_IMMUTABLE',
  POSITION_IMPACT_CONFIRMATION_REQUIRED: 'ORG_POSITION_IMPACT_CONFIRMATION_REQUIRED',
  POSITION_POLICY_INVALID_ACTION: 'ORG_POSITION_POLICY_INVALID_ACTION',
  POSITION_POLICY_NOT_GRANTABLE: 'ORG_POSITION_POLICY_NOT_GRANTABLE',
  POSITION_POLICY_CEILING_EXCEEDED: 'ORG_POSITION_POLICY_CEILING_EXCEEDED',
  POSITION_POLICY_NOT_FOUND: 'ORG_POSITION_POLICY_NOT_FOUND',
  REPORTING_MANAGER_INVALID: 'ORG_INVALID_MANAGER',
  REPORTING_CYCLE: 'ORG_REPORTING_CYCLE',
  REPORTING_SELF_ASSIGNMENT: 'ORG_REPORTING_SELF_ASSIGNMENT',
  REPORTING_POSITION_INVALID: 'ORG_REPORTING_POSITION_INVALID',
  REPORTING_SUBTREE_CONFIRMATION_REQUIRED: 'ORG_REPORTING_SUBTREE_CONFIRMATION_REQUIRED',
  REPORTING_SUBTREE_NOT_VISIBLE: 'ORG_REPORTING_SUBTREE_NOT_VISIBLE',
  CHART_VISIBILITY_DENIED: 'ORG_VISIBILITY_DENIED',
} as const;

export class OrganizationValidationError extends ApplicationError {
  constructor(code: string, message: string, details?: unknown) {
    super(message, 422, code, details);
    this.name = 'OrganizationValidationError';
  }
}

export class OrganizationConflictError extends ApplicationError {
  constructor(code: string, message: string, details?: unknown) {
    super(message, 409, code, details);
    this.name = 'OrganizationConflictError';
  }
}

export class OrganizationNotFoundError extends ApplicationError {
  constructor(code: string, message: string) {
    super(message, 404, code);
    this.name = 'OrganizationNotFoundError';
  }
}
