import { useEffect, useState } from 'react';
import { Button, Card, Page, Select, SkeletonDetail } from '../../../ui/components.js';
import { callbackOutcome, getCallback, getCallbacks, getLead, updateCallback, type Lead, type LeadCallback } from './api.js';
import { formatCallbackDate, organizationLocalToIso } from './callback-ui.js';

export function CallbackDetailPage({ id, currentUserId, onBack, onNavigate }: { id: string; currentUserId: string; onBack: () => void; onNavigate: (path: string) => void }): React.JSX.Element {
  const [callback, setCallback] = useState<LeadCallback | null>(null); const [lead, setLead] = useState<Lead | null>(null); const [history, setHistory] = useState<LeadCallback[]>([]); const [rescheduleAt, setRescheduleAt] = useState(''); const [outcome, setOutcome] = useState('connected'); const [error, setError] = useState('');
  const reload = () => getCallback(id).then(async (next) => { setCallback(next); const [nextLead, nextHistory] = await Promise.all([getLead(next.leadId), getCallbacks(next.leadId)]); setLead(nextLead); setHistory(nextHistory); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Unable to load callback.'));
  useEffect(() => { void reload(); }, [id]);
  if (error) return <Page eyebrow="Sales" title="Callback"><p className="text-sm text-app-danger">{error}</p><Button className="mt-4" kind="secondary" onClick={onBack}>Back</Button></Page>;
  if (!callback) return <Page eyebrow="Sales" title="Callback"><SkeletonDetail sections={2} /></Page>;
  const canOperate = callback.ownerId === currentUserId; const run = async (action: () => Promise<unknown>) => { try { await action(); setError(''); await reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Callback action failed.'); } };
  return <Page eyebrow="Sales" title="Callback detail" description={lead ? `${lead.contactName} · Lead #${lead.leadNumber}` : `Lead ${callback.leadId}`} action={<Button kind="secondary" onClick={onBack}>Back to callbacks</Button>}>
    {error && <p className="mb-4 text-sm text-app-danger">{error}</p>}<div className="grid gap-6 lg:grid-cols-3"><Card className="lg:col-span-2"><div className="grid gap-4 sm:grid-cols-2"><Info label="Status" value={callback.status.replaceAll('_', ' ')} /><Info label="Owner" value={callback.ownerName ?? 'Unknown'} /><Info label="Scheduled" value={formatCallbackDate(callback.scheduledAt, callback.organizationTimezone)} /><Info label="Outcome" value={callback.outcome?.replaceAll('_', ' ') ?? '—'} /><Info label="Reason" value={callback.reason ?? '—'} /><Info label="Reminder timezone" value={callback.organizationTimezone} /></div>{canOperate && callback.status === 'pending' && <div className="mt-6 space-y-3 border-t border-app-border pt-5"><div className="flex flex-wrap gap-2"><Button onClick={() => void run(() => callbackOutcome(callback.id, 'completed', outcome))}>Complete</Button><Button kind="secondary" onClick={() => void run(() => callbackOutcome(callback.id, 'not_reachable', 'not_reachable'))}>Not reachable</Button><Button kind="danger" onClick={() => void run(() => callbackOutcome(callback.id, 'cancelled'))}>Cancel</Button></div><Select label="Completion outcome" value={outcome} onChange={setOutcome} options={['connected', 'follow_up_required', 'converted', 'not_interested', 'other'].map((value) => ({ value, label: value.replaceAll('_', ' ') }))} /><div className="flex gap-2"><input type="datetime-local" value={rescheduleAt} onChange={(event) => setRescheduleAt(event.target.value)} className="rounded-lg border border-app-border bg-app-background px-3 py-2 text-sm" /><Button kind="secondary" disabled={!rescheduleAt} onClick={() => void run(() => updateCallback(callback.id, { scheduledAt: organizationLocalToIso(rescheduleAt, callback.organizationTimezone) }))}>Reschedule</Button></div></div>}</Card><ReminderCard callback={callback} /><Card className="lg:col-span-3"><h2 className="font-display text-lg font-bold">Callback history</h2><div className="mt-4 space-y-2">{history.sort((a, b) => new Date(a.scheduledAt).getTime() - new Date(b.scheduledAt).getTime()).map((item) => <button key={item.id} onClick={() => item.id !== callback.id && onNavigate(`/company/sales/callbacks/${item.id}`)} className={`block w-full rounded-lg border p-3 text-left text-sm ${item.id === callback.id ? 'border-app-accent' : 'border-app-border'}`}><span className="font-semibold">{formatCallbackDate(item.scheduledAt, item.organizationTimezone)}</span> · {item.status.replaceAll('_', ' ')}{item.parentCallbackId ? ' · rescheduled from previous callback' : ''}</button>)}</div></Card></div>
  </Page>;
}

function Info({ label, value }: { label: string; value: string }): React.JSX.Element { return <div><p className="text-xs font-semibold uppercase tracking-wide text-app-muted">{label}</p><p className="mt-1 font-semibold capitalize">{value}</p></div>; }
function ReminderCard({ callback }: { callback: LeadCallback }): React.JSX.Element { return <Card><h2 className="font-display text-lg font-bold">Reminders</h2><div className="mt-4 space-y-3">{callback.reminders.length === 0 ? <p className="text-sm text-app-muted">No reminder events have been generated yet.</p> : callback.reminders.map((reminder) => <div key={reminder.id} className="border-b border-app-border pb-3 text-sm"><p className="font-semibold">{reminder.reminderType.replaceAll('_', ' ')}</p><p className="text-xs text-app-muted">{formatCallbackDate(reminder.scheduledAt, callback.organizationTimezone)}</p>{reminder.deliveries.map((delivery) => <p key={delivery.id} className="mt-1 text-xs">{delivery.channel}: <span className="font-semibold">{delivery.status}</span>{delivery.detail ? ` · ${delivery.detail}` : ''}</p>)}</div>)}</div></Card>; }
