import { useEffect, useState } from 'react';
import { Button, Card, Field, Page } from '../../../ui/components.js';
import { createLead, createLeadSource, getCampaigns, getLeadSources, getLeads, type Campaign, type Lead, type LeadSource } from './api.js';

export function LeadsPage({ onNavigate }: { onNavigate: (path: string) => void }): React.JSX.Element {
  const [items, setItems] = useState<Lead[]>([]); const [sources, setSources] = useState<LeadSource[]>([]); const [campaigns, setCampaigns] = useState<Campaign[]>([]); const [open, setOpen] = useState(false); const [sourceOpen, setSourceOpen] = useState(false); const [error, setError] = useState('');
  const reload = () => Promise.all([getLeads(), getLeadSources(), getCampaigns()]).then(([page, nextSources, nextCampaigns]) => { setItems(page.items); setSources(nextSources); setCampaigns(nextCampaigns); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Unable to load leads.'));
  useEffect(() => { void reload(); }, []);
  const [duplicates, setDuplicates] = useState<Array<{ leadId: string; leadNumber: string; ownerName: string | null }>>([]);
  return <Page eyebrow="Sales" title="Leads" description="Capture and review sales leads. Routing follows the configured Territories foundation when applicable." action={<div className="flex gap-2"><Button kind="secondary" onClick={() => onNavigate('/company/sales/leads/re-engagement')}>Re-engagement</Button><Button kind="secondary" onClick={() => onNavigate('/company/sales/leads/stalled')}>Stalled queue</Button><Button onClick={() => setOpen(true)}>New Lead</Button></div>}>
    {error && <p className="mb-4 rounded-lg bg-[#d86b6b]/10 p-3 text-sm text-app-danger">{error}</p>}
    {duplicates.length > 0 && <Card className="mb-6 border border-amber-500/40 bg-amber-500/10"><p className="font-semibold">Possible duplicate lead created</p><p className="mt-1 text-sm text-app-muted">Review these existing records before continuing outreach: {duplicates.map((duplicate) => `#${duplicate.leadNumber}${duplicate.ownerName ? ` (${duplicate.ownerName})` : ''}`).join(', ')}.</p></Card>}
    {open && <LeadForm sources={sources} campaigns={campaigns} onCancel={() => setOpen(false)} onSave={async (input) => { try { const result = await createLead(input); setDuplicates(result.duplicates); setOpen(false); await reload(); if (!result.duplicates.length) onNavigate(`/company/sales/leads/${result.lead.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create lead.'); } }} />}
    {sourceOpen && <SourceForm onCancel={() => setSourceOpen(false)} onSave={async (input) => { try { await createLeadSource(input); setSourceOpen(false); await reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create source.'); } }} />}
    <Card className="mb-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-xl font-bold">Lead sources</h2><p className="mt-1 text-sm text-app-muted">Inbound sources participate in routing; outbound sources remain with the creator.</p></div><Button kind="secondary" onClick={() => setSourceOpen(true)}>New source</Button></div><div className="mt-4 flex flex-wrap gap-2">{sources.map((source) => <span key={source.id} className="rounded-full bg-app-background px-3 py-1.5 text-xs font-semibold">{source.name} · {source.direction}</span>)}{sources.length === 0 && <span className="text-sm text-app-muted">No sources configured.</span>}</div></Card>
    <Card className="overflow-hidden p-0">{items.length === 0 ? <div className="p-6"><h2 className="font-display text-xl font-bold">No leads yet</h2><p className="mt-2 text-sm text-app-muted">Create a lead after configuring at least one source.</p></div> : <div className="divide-y divide-app-border">{items.map((lead) => <button key={lead.id} className="flex w-full flex-wrap items-center justify-between gap-4 p-5 text-left hover:bg-app-background" onClick={() => onNavigate(`/company/sales/leads/${lead.id}`)}><div><p className="font-display text-lg font-bold">{lead.contactName}</p><p className="mt-1 text-sm text-app-muted">#{lead.leadNumber} · {lead.companyName ?? 'No company'} · {lead.sourceName}{lead.campaignName ? ` · ${lead.campaignName}` : ''}</p></div><div className="text-right text-xs"><span className="rounded-full bg-app-background px-3 py-1 font-bold">{lead.status.replaceAll('_', ' ')}</span><p className="mt-2 text-app-muted">{lead.routingStatus === 'assigned' ? lead.ownerName ?? 'Assigned' : 'Unrouted'}</p></div></button>)}</div>}</Card>
  </Page>;
}

function LeadForm({ sources, campaigns, onCancel, onSave }: { sources: LeadSource[]; campaigns: Campaign[]; onCancel: () => void; onSave: (input: { contactName: string; companyName?: string | undefined; phone?: string | undefined; email?: string | undefined; sourceId: string; campaignId?: string | undefined }) => Promise<void> }): React.JSX.Element {
  const [contactName, setContactName] = useState(''); const [companyName, setCompanyName] = useState(''); const [phone, setPhone] = useState(''); const [email, setEmail] = useState(''); const [sourceId, setSourceId] = useState(sources[0]?.id ?? ''); const [campaignId, setCampaignId] = useState('');
  return <Card className="mb-6"><h2 className="font-display text-xl font-bold">New lead</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Contact name" value={contactName} onChange={setContactName} required /><Field label="Company" value={companyName} onChange={setCompanyName} /><Field label="Phone" value={phone} onChange={setPhone} /><Field label="Email" value={email} onChange={setEmail} type="email" /><label className="text-xs font-semibold text-app-muted"><span className="mb-2 block">Source</span><select value={sourceId} onChange={(event) => setSourceId(event.target.value)} className="w-full rounded-lg border border-app-border bg-app-background px-3 py-2.5 text-sm" required><option value="">Select source</option>{sources.filter((source) => source.status === 'active').map((source) => <option key={source.id} value={source.id}>{source.name}</option>)}</select></label><label className="text-xs font-semibold text-app-muted"><span className="mb-2 block">Campaign</span><select value={campaignId} onChange={(event) => setCampaignId(event.target.value)} className="w-full rounded-lg border border-app-border bg-app-background px-3 py-2.5 text-sm"><option value="">No campaign</option>{campaigns.filter((campaign) => campaign.status === 'active').map((campaign) => <option key={campaign.id} value={campaign.id}>{campaign.name}</option>)}</select></label></div><div className="mt-5 flex justify-end gap-3"><Button kind="secondary" onClick={onCancel}>Cancel</Button><Button disabled={!contactName.trim() || (!phone.trim() && !email.trim()) || !sourceId} onClick={() => void onSave({ contactName: contactName.trim(), companyName: companyName.trim() || undefined, phone: phone.trim() || undefined, email: email.trim() || undefined, sourceId, campaignId: campaignId || undefined })}>Create lead</Button></div></Card>;
}

function SourceForm({ onCancel, onSave }: { onCancel: () => void; onSave: (input: { name: string; direction: 'inbound' | 'outbound' }) => Promise<void> }): React.JSX.Element {
  const [name, setName] = useState(''); const [direction, setDirection] = useState<'inbound' | 'outbound'>('inbound');
  return <Card className="mb-6"><h2 className="font-display text-xl font-bold">New lead source</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Name" value={name} onChange={setName} required /><label className="text-xs font-semibold text-app-muted"><span className="mb-2 block">Direction</span><select value={direction} onChange={(event) => setDirection(event.target.value as 'inbound' | 'outbound')} className="w-full rounded-lg border border-app-border bg-app-background px-3 py-2.5 text-sm"><option value="inbound">Inbound</option><option value="outbound">Outbound</option></select></label></div><div className="mt-5 flex justify-end gap-3"><Button kind="secondary" onClick={onCancel}>Cancel</Button><Button disabled={!name.trim()} onClick={() => void onSave({ name: name.trim(), direction })}>Create source</Button></div></Card>;
}
