import { useEffect, useState } from 'react';
import { Button, Card, Field, Page } from '../../../ui/components.js';
import { acceptHandover, addHandoverAnnotation, declineHandover, getAllHandovers, recordHandoverDisposition, type Handover } from '../leads/api.js';

type HandoverView = 'all' | 'incoming' | 'mine';

export function HandoverPage({ view, currentUserId, onNavigate }: { view: HandoverView; currentUserId: string; onNavigate: (path: string) => void }): React.JSX.Element {
  const [items, setItems] = useState<Handover[]>([]); const [selected, setSelected] = useState<Handover | null>(null); const [error, setError] = useState('');
  const reload = (): Promise<void> => getAllHandovers().then((rows) => { const visible = view === 'incoming' ? rows.filter((row) => row.status === 'pending' && (row.toUserId === currentUserId || (row.handoverMode === 'team_queue' && row.toUserId === null))) : view === 'mine' ? rows.filter((row) => row.fromUserId === currentUserId || row.toUserId === currentUserId) : rows; setItems(visible); if (selected) setSelected(visible.find((row) => row.id === selected.id) ?? null); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Unable to load handovers.'));
  useEffect(() => { void reload(); }, [view]);
  return <Page eyebrow="Sales" title="Handovers" description="Review authorized Sales handover workflow and operational outcomes." action={<div className="flex flex-wrap gap-2"><Button kind={view === 'all' ? 'primary' : 'secondary'} onClick={() => onNavigate('/company/sales/handovers')}>All</Button><Button kind={view === 'incoming' ? 'primary' : 'secondary'} onClick={() => onNavigate('/company/sales/handovers/incoming')}>Incoming Offers</Button><Button kind={view === 'mine' ? 'primary' : 'secondary'} onClick={() => onNavigate('/company/sales/handovers/mine')}>My Handovers</Button></div>}>
    {error && <p className="mb-4 rounded-lg bg-[#d86b6b]/10 p-3 text-sm text-app-danger">{error}</p>}
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(18rem,0.8fr)]"><Card className="overflow-hidden p-0"><div className="divide-y divide-app-border">{items.length === 0 ? <p className="p-6 text-sm text-app-muted">No authorized handovers found.</p> : items.map((row) => <button key={row.id} onClick={() => setSelected(row)} className={`block w-full p-4 text-left hover:bg-app-background ${selected?.id === row.id ? 'bg-app-background' : ''}`}><div className="flex flex-wrap items-center justify-between gap-3"><span className="font-semibold">{row.handoverMode === 'team_queue' ? 'Sales team queue' : `Lead handover · ${row.toUserName ?? 'receiver'}`}</span><span className="rounded-full bg-app-background px-2.5 py-1 text-xs font-bold capitalize">{row.disposition ?? row.status}</span></div><p className="mt-1 text-xs text-app-muted">{row.fromUserName ?? 'Original holder'} → {row.toUserName ?? 'Unclaimed'} · {new Date(row.offeredAt).toLocaleString()}</p></button>)}</div></Card>{selected ? <HandoverDetail handover={selected} currentUserId={currentUserId} onUpdated={reload} /> : <Card><p className="text-sm text-app-muted">Select a Handover to review its authorized details and actions.</p></Card>}</div>
  </Page>;
}

function HandoverDetail({ handover, currentUserId, onUpdated }: { handover: Handover; currentUserId: string; onUpdated: () => Promise<void> }): React.JSX.Element {
  const [reason, setReason] = useState(''); const [annotation, setAnnotation] = useState(''); const [error, setError] = useState('');
  const run = async (action: () => Promise<unknown>) => { try { await action(); setError(''); await onUpdated(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Handover action failed.'); } };
  const receiver = handover.toUserId === currentUserId; const canClaim = handover.handoverMode === 'team_queue' && handover.toUserId === null;
  return <Card><h2 className="font-display text-lg font-bold">Handover detail</h2>{error && <p className="mt-3 text-sm text-app-danger">{error}</p>}<dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Info label="Status" value={handover.disposition ?? handover.status} /><Info label="Mode" value={handover.handoverMode === 'team_queue' ? 'Sales team queue' : 'Direct'} /><Info label="Time to accept" value={formatSeconds(handover.timeToAcceptSeconds)} /><Info label="Time to outcome" value={formatSeconds(handover.timeToOutcomeSeconds)} /><Info label="Offered" value={new Date(handover.offeredAt).toLocaleString()} /><Info label="Lead" value={handover.leadId} /></dl>{(canClaim || (receiver && handover.status === 'pending')) && <div className="mt-5 flex flex-wrap gap-2">{(canClaim || receiver) && <Button onClick={() => void run(() => acceptHandover(handover.id))}>Accept / Claim</Button>}{receiver && <><Field label="Decline reason" value={reason} onChange={setReason} /><Button kind="secondary" disabled={!reason.trim()} onClick={() => void run(() => declineHandover(handover.id, reason.trim()))}>Decline</Button></>}</div>}{receiver && handover.status === 'accepted' && !handover.disposition && <div className="mt-5 flex flex-wrap gap-2"><Button onClick={() => void run(() => recordHandoverDisposition(handover.id, 'accepted'))}>Finalize accepted</Button><Button kind="secondary" onClick={() => void run(() => recordHandoverDisposition(handover.id, 'callback', undefined, new Date(Date.now() + 3600000).toISOString()))}>Callback +1h</Button><Button kind="danger" onClick={() => void run(() => recordHandoverDisposition(handover.id, 'rejected', 'Rejected from Handover detail', undefined, 'other'))}>Reject</Button></div>}{handover.corrections.length > 0 && <div className="mt-5 border-t border-app-border pt-4"><p className="text-xs font-bold uppercase tracking-wide text-app-muted">Annotations</p>{handover.corrections.map((item) => <p key={item.id} className="mt-2 text-sm">{item.annotation}</p>)}</div>}{<div className="mt-5 border-t border-app-border pt-4"><Field label="Add correction / note" value={annotation} onChange={setAnnotation} /><Button className="mt-3" kind="secondary" disabled={!annotation.trim()} onClick={() => void run(() => addHandoverAnnotation(handover.id, annotation.trim()))}>Add annotation</Button></div>}</Card>;
}

function Info({ label, value }: { label: string; value: string }): React.JSX.Element { return <div><p className="text-xs font-bold uppercase tracking-wide text-app-muted">{label}</p><p className="mt-1 font-semibold capitalize">{value}</p></div>; }
function formatSeconds(value: number | null): string { return value === null ? '—' : `${value}s`; }
