import { useEffect, useState } from 'react';
import { Button, Card, Page } from '../../../ui/components.js';
import { getTerritory, getTerritoryCoverage, reassignTerritory, type Territory, type TerritoryCoverage } from '../api.js';
import { getCompanyTeams, type CompanyTeam } from '../../api/companyApi.js';

export function TerritoryDetailsPage({ id, onBack, canManage }: { id: string; onBack: () => void; canManage: boolean }): React.JSX.Element {
  const [territory, setTerritory] = useState<Territory | null>(null);
  const [coverage, setCoverage] = useState<TerritoryCoverage | null>(null);
  const [teams, setTeams] = useState<CompanyTeam[]>([]); const [newTeamId, setNewTeamId] = useState(''); const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => { void getTerritory(id).then((next) => { setTerritory(next); setNewTeamId(next.salesTeamId); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Unable to load territory.')); void getTerritoryCoverage().then((rows) => setCoverage(rows.find((row) => row.territoryId === id) ?? null)); if (canManage) void getCompanyTeams().then(setTeams); }, [id, canManage]);
  if (error) return <Page title="Territory"><p className="text-app-danger">{error}</p></Page>;
  if (!territory) return <Page title="Territory"><p className="text-sm text-app-muted">Loading territory...</p></Page>;
  const grouped = new Map<string, string[]>();
  for (const rule of territory.rules) grouped.set(rule.dimension, [...(grouped.get(rule.dimension) ?? []), rule.value]);
  const saveTeam = () => { if (!newTeamId || newTeamId === territory.salesTeamId || !window.confirm('Reassign "' + territory.name + '" from ' + territory.salesTeamName + ' to the selected Sales Team? Existing Leads will remain unchanged.')) return; setSaving(true); void reassignTerritory(territory.id, newTeamId).then((next) => { setTerritory(next); setCoverage(null); return getTerritoryCoverage().then((rows) => setCoverage(rows.find((row) => row.territoryId === id) ?? null)); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Unable to reassign territory.')).finally(() => setSaving(false)); };
  return <Page eyebrow="Sales / Territories" title={territory.name} action={<Button kind="secondary" onClick={onBack}>Back to Territories</Button>}><div className="grid gap-5 lg:grid-cols-3"><Card className="lg:col-span-2"><h2 className="font-display text-xl font-bold">Configuration</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs font-bold uppercase tracking-wide text-app-muted">Sales Team</dt><dd className="mt-1">{territory.salesTeamName}</dd></div><div><dt className="text-xs font-bold uppercase tracking-wide text-app-muted">Status</dt><dd className="mt-1 capitalize">{territory.status}</dd></div><div className="sm:col-span-2"><dt className="text-xs font-bold uppercase tracking-wide text-app-muted">Description</dt><dd className="mt-1 text-sm text-app-muted">{territory.description || 'No description provided.'}</dd></div></dl>{canManage && <div className="mt-6 border-t border-app-border pt-5"><h3 className="font-bold">Reassign Sales Team</h3><p className="mt-1 text-sm text-app-muted">Current: {territory.salesTeamName}. This changes future inbound routing only; existing Leads remain unchanged.</p><div className="mt-3 flex flex-wrap gap-3"><select value={newTeamId} onChange={(e) => setNewTeamId(e.target.value)} className="min-w-56 rounded-lg border border-app-border bg-app-background px-3 py-2.5 text-sm">{teams.filter((team) => team.kind === 'sales-team').map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select><Button disabled={saving || newTeamId === territory.salesTeamId} onClick={saveTeam}>{saving ? 'Reassigning…' : 'Reassign Territory'}</Button></div></div>}{coverage && <div className="mt-6 border-t border-app-border pt-5"><h3 className="font-bold">Operational context</h3><p className="mt-2 text-sm text-app-muted">Child Sales Pools: {coverage.salesPools.length ? coverage.salesPools.map((pool) => pool.name).join(', ') : 'None configured'}</p><p className="mt-2 text-sm text-app-muted">Routing: {coverage.routingEnabled ? coverage.assignmentStrategy.replaceAll('_', ' ') : 'Disabled'}</p><p className="mt-2 text-sm text-app-muted">Future metrics: Agents — · Punched in — · Open leads — · Unrouted leads —</p></div>}</Card><Card><h2 className="font-display text-xl font-bold">Matching Rules</h2>{grouped.size === 0 ? <p className="mt-4 text-sm text-app-muted">No matching criteria configured.</p> : <div className="mt-4 space-y-4">{[...grouped.entries()].map(([dimension, values]) => <div key={dimension}><p className="text-xs font-bold uppercase tracking-wide text-app-muted">{dimension.replace('_', ' ')}</p><ul className="mt-1 list-disc pl-5 text-sm">{values.map((value) => <li key={value}>{value}</li>)}</ul></div>)}</div>}</Card></div></Page>;
}
