import { useEffect, useState } from 'react';
import {
  formatDate,
  formatMonth,
  formatPaise,
  getSlipDetail,
  listMySlips,
  type SlipDetail,
  type SlipSummary,
} from '../api/payrollApi.js';
import { Button, Card, Notice, Page, SkeletonTable } from '../../ui/components.js';

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c] ?? c);
}

/** A print-ready payslip in its own window: the browser's print dialog saves it as PDF. */
function printPayslip(detail: SlipDetail): void {
  const rows = (kind: 'earning' | 'deduction') =>
    detail.lines
      .filter((line) => line.kind === kind)
      .map((line) => `<tr><td>${escapeHtml(line.label)}</td><td class="n">${escapeHtml(formatPaise(line.amountPaise))}</td></tr>`)
      .join('') || '<tr><td colspan="2" class="m">None</td></tr>';
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Payslip ${escapeHtml(formatMonth(detail.periodStart))} - ${escapeHtml(detail.fullName)}</title>
<style>
body{font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;color:#111;margin:32px;}
h1{font-size:20px;margin:0}h2{font-size:14px;margin:24px 0 8px;text-transform:uppercase;letter-spacing:.08em;color:#555}
.meta{display:grid;grid-template-columns:1fr 1fr;gap:4px 24px;margin-top:16px;font-size:13px}
table{width:100%;border-collapse:collapse;font-size:13px}td{padding:6px 0;border-bottom:1px solid #eee}.n{text-align:right;font-variant-numeric:tabular-nums}.m{color:#888}
.cols{display:grid;grid-template-columns:1fr 1fr;gap:32px}.total{font-weight:700}
.net{margin-top:24px;padding:12px 16px;border:2px solid #111;display:flex;justify-content:space-between;font-size:16px;font-weight:700}
.foot{margin-top:24px;font-size:11px;color:#666}
</style></head><body>
<h1>${escapeHtml(detail.organizationName ?? '')}</h1>
<p style="margin:4px 0 0;color:#555">Payslip for ${escapeHtml(formatMonth(detail.periodStart))}${detail.revisionNumber > 0 ? ` (revision ${detail.revisionNumber})` : ''}</p>
<div class="meta">
<div><b>Employee:</b> ${escapeHtml(detail.fullName)}</div><div><b>Employee ID:</b> ${escapeHtml(detail.employeeCode ?? '—')}</div>
<div><b>Department:</b> ${escapeHtml(detail.departmentName ?? '—')}</div><div><b>Position:</b> ${escapeHtml(detail.positionName ?? '—')}</div>
<div><b>Period:</b> ${escapeHtml(formatDate(detail.periodStart))} – ${escapeHtml(formatDate(detail.periodEnd))}</div><div><b>Published:</b> ${escapeHtml(formatDate(detail.publishedAt))}</div>
</div>
<div class="cols">
<div><h2>Earnings</h2><table>${rows('earning')}<tr class="total"><td>Gross</td><td class="n">${escapeHtml(formatPaise(detail.grossPaise))}</td></tr></table></div>
<div><h2>Deductions</h2><table>${rows('deduction')}<tr class="total"><td>Total deductions</td><td class="n">${escapeHtml(formatPaise(detail.deductionsPaise))}</td></tr></table></div>
</div>
<div class="net"><span>Net pay</span><span>${escapeHtml(formatPaise(detail.netPaise))}</span></div>
<p class="foot">This payslip was generated by TapCRM.</p>
<script>window.onload=function(){window.print();}</script>
</body></html>`;
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.open();
  win.document.write(html);
  win.document.close();
}

function SlipView({ slip, onClose }: { slip: SlipSummary; onClose: () => void }): React.JSX.Element {
  const [detail, setDetail] = useState<SlipDetail | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setDetail(null);
    setError(null);
    getSlipDetail(slip.id)
      .then((d) => { if (d) setDetail(d); else setError('This payslip is not available.'); })
      .catch((err: unknown) => setError(err instanceof Error ? err.message : 'Unable to load the payslip.'));
  }, [slip.id]);

  return (
    <Card className="mt-6 space-y-4">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <p className="text-xs font-semibold uppercase tracking-wider text-app-muted">Payslip</p>
          <h2 className="mt-1 font-display text-2xl font-bold">{formatMonth(slip.periodStart)}</h2>
          {slip.revisionNumber > 0 && <p className="text-xs text-app-muted">Revision {slip.revisionNumber} — replaces the earlier payslip for this month</p>}
        </div>
        <div className="flex gap-2">
          {detail && <Button kind="secondary" onClick={() => printPayslip(detail)}>Print / save PDF</Button>}
          <Button kind="secondary" onClick={onClose}>Close</Button>
        </div>
      </div>
      {error && <Notice error>{error}</Notice>}
      {!detail && !error && <p className="text-sm text-app-muted">Loading…</p>}
      {detail && (
        <>
          <div className="grid gap-3 sm:grid-cols-3">
            {[
              { label: 'Gross', value: formatPaise(detail.grossPaise) },
              { label: 'Deductions', value: formatPaise(detail.deductionsPaise) },
              { label: 'Net pay', value: formatPaise(detail.netPaise) },
            ].map(({ label, value }) => (
              <div key={label} className="rounded-xl border border-app-border p-3">
                <p className="text-[11px] font-semibold uppercase tracking-wider text-app-muted">{label}</p>
                <p className="mt-0.5 text-lg font-bold tabular-nums">{value}</p>
              </div>
            ))}
          </div>
          <div className="grid gap-6 md:grid-cols-2">
            {(['earning', 'deduction'] as const).map((kind) => (
              <div key={kind}>
                <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-app-muted">{kind === 'earning' ? 'Earnings' : 'Deductions'}</p>
                {detail.lines.filter((line) => line.kind === kind).map((line) => (
                  <div key={line.code} className="flex justify-between border-b border-app-border py-1.5 text-sm last:border-0">
                    <span>{line.label}</span>
                    <span className="tabular-nums">{formatPaise(line.amountPaise)}</span>
                  </div>
                ))}
                {detail.lines.every((line) => line.kind !== kind) && <p className="text-sm text-app-muted">None</p>}
              </div>
            ))}
          </div>
        </>
      )}
    </Card>
  );
}

export function MyPayslipsPage(): React.JSX.Element {
  const [slips, setSlips] = useState<SlipSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);

  useEffect(() => {
    listMySlips()
      .then((data) => setSlips(data.slips))
      .catch((err: unknown) => setError(err instanceof Error ? err.message : 'Unable to load payslips.'))
      .finally(() => setLoading(false));
  }, []);

  const selected = slips.find((s) => s.id === selectedId) ?? null;

  return (
    <Page eyebrow="Payroll" title="My payslips" description="Your published payslips. A corrected month shows its latest revision.">
      {error && <div className="mt-6"><Notice error>{error}</Notice></div>}
      {loading && <div className="mt-6"><SkeletonTable columns={4} rows={5} /></div>}
      {!loading && slips.length === 0 && !error && (
        <Card className="mt-6 text-center"><p className="text-sm text-app-muted">No published payslips yet.</p></Card>
      )}
      {selected && <SlipView slip={selected} onClose={() => setSelectedId(null)} />}
      {slips.length > 0 && (
        <div className="mt-6 overflow-x-auto rounded-2xl border border-app-border bg-app-surface">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-app-border text-left text-xs uppercase tracking-wider text-app-muted">
                <th className="px-4 py-3">Month</th>
                <th className="px-4 py-3 text-right">Gross</th>
                <th className="px-4 py-3 text-right">Deductions</th>
                <th className="px-4 py-3 text-right">Net pay</th>
                <th className="px-4 py-3" />
              </tr>
            </thead>
            <tbody>
              {slips.map((slip) => (
                <tr key={slip.id} className={`border-b border-app-border last:border-0 ${slip.id === selectedId ? 'bg-app-accent/5' : ''}`}>
                  <td className="px-4 py-3 font-medium">
                    {formatMonth(slip.periodStart)}
                    {slip.revisionNumber > 0 && <span className="ml-2 text-xs text-app-muted">revised</span>}
                  </td>
                  <td className="px-4 py-3 text-right tabular-nums text-app-muted">{formatPaise(slip.grossPaise)}</td>
                  <td className="px-4 py-3 text-right tabular-nums text-app-muted">{formatPaise(slip.deductionsPaise)}</td>
                  <td className="px-4 py-3 text-right font-semibold tabular-nums">{formatPaise(slip.netPaise)}</td>
                  <td className="px-4 py-3 text-right">
                    <Button kind="secondary" onClick={() => setSelectedId(slip.id === selectedId ? null : slip.id)}>
                      {slip.id === selectedId ? 'Hide' : 'View'}
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </Page>
  );
}
